
import { Roboto } from 'next/font/google';
import {Toaster} from "react-hot-toast";
import './globals.css';
import Navbar from '@/components/Navbar';
import ContextProvider from '@/components/ContextProvider';

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] });

export const metadata = {
  title: 'Market Place',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={roboto.className}>
        <ContextProvider>
         <Toaster />
          <main className="max-w-4xl mx-auto p-4 overflow-y-hidden">
            <Navbar />
            {children}
          </main>
        </ContextProvider>
      </body>
    </html>
  );
}
