import { Roboto } from "next/font/google";
import { Toaster } from "@/components/ui/toaster"
import "@/styles/globals.css";
import ContextProvider from "@/components/commons/ContextProvider";
import Container from "@/components/commons/Container";
import { NavBar } from "@/components/nav-bar";
import { CartProvider } from "@/components/cart-provider";
import ChatBot from "@/components/commons/ChatBot";
import { Footer } from "@/components/footer";
import { ThemeProvider } from "@/components/theme-provider";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Market Place",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth overflow-x-hidden">
      <body className={`${roboto.className} flex min-h-screen flex-col`}>
        <CartProvider>
          <ContextProvider>
            <NavBar />
            
            
            <main className="flex-1 max-w-7xl mx-auto py-4 px-[10px] overflow-y-hidden">
              {children}
            </main>
            <ChatBot /> {/* Add the chatbot here */}
            <Footer />
            <Toaster />
            <ThemeProvider />
          </ContextProvider>
        </CartProvider>
      </body>
    </html>
  );
}